### ISSUE TITLE
add maxTries argument for simFossilRecord()

### ISSUE THREAD

**Issue by wabarr** [dwbapst/paleotree#1]
It would be great to add a `maxTries` argument for `simFossilRecord()`, such that if the user specifies a combination of parameters that results in an infinite loop, the function will give up after a time.

**Comment by dwbapst** [comment]
Great suggestion! Now implemented as argument `maxAttempts` which defaults to infinity (so that previous behavior is retained). Here's a short example:

```
> # install_github("dwbapst/paleotree")
> 
> record <- simFossilRecord(p=0.1, q=0.1, r=0.1, nruns=1, 
+ nTotalTaxa=c(1,100), nExtant=0, nSamp=20,
+ print.runs=TRUE, plot=TRUE, maxAttempts=10)
Error in simFossilRecord(p = 0.1, q = 0.1, r = 0.1, nruns = 1, nTotalTaxa = c(1,  : 
  Maximum number of attempts (10) has been exceeded with only 0 run(s) successful.
```

Looks like it works fine!

**Comment by wabarr** [comment]
awesome.  Thanks!
