### ISSUE TITLE
Error in bin_timePaleoPhy(ParTree, timeList = TimeGenus, nonstoch.bin = TRUE,  :    timeList[[1]] not in intervals in time relative to modern

### ISSUE THREAD

**Issue by RussellGrayxd** [dwbapst/paleotree#20]
using the "bin_timePaleoPhy" function:

Can't figure out how to fix this error... At first it said "unexpected NA" were the issue... so I removed necessary rows with unnecessary NAs. Now it says this. 

I've successfully run the same code with other taxa, but for some reason this one is giving me all sorts of issues.... using "Salamandridae" as my family and ancestry set to children. 

Any help would be greatly appreciated.

**Comment by dwbapst** [comment]
Hi @RussellGrayxd,

Could you maybe show the output message itself, just copy/paste it here? It would also be useful if you could run `traceback()` after you get the error and past the output it returns, so I can see what line the error occurs on.

> using "Salamandridae" as my family and ancestry set to children.

Not certain what you mean by that last part. What are you doing with ancestry?

**Comment by dwbapst** [comment]
Another thing I'd like to see is the version of the package you are using, you can get that with

```
packageVersion("paleotree")
```

**Comment by RussellGrayxd** [comment]
Hey, thanks for the reply!
I figured out the issue... there are a few records from PaleobioDB that have backwards first and last appearance data in the Salamandridae family, they were messing with the code. I just omitted them and it worked fine. 
Best,

-Russell Gray
    On Monday, May 13, 2019, 9:13:57 p.m. GMT+7, David Bapst <notifications@github.com> wrote:  
 
 
Another thing I'd like to see is the version of the package you are using, you can get that with
packageVersion("paleotree")

**Comment by dwbapst** [comment]
Gotcha!
